version: '3.7'

services:
  sap_profile_db:
    image: mysql:latest
    container_name: sap_db
    ports:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Camacho.123
      MYSQL_ROOT_HOST: '0.0.0.0' 
    volumes:
      - ./mysql:/var/lib/mysql
