version: '3.7'

services:
  sap_profile_ms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        ConnectionString: server=ec2-54-237-187-136.compute-1.amazonaws.com;port=3306;database=sap_profile_db;user=root;password=Camacho.123;Protocol=tcp
    ports:
      - "8000:80"
