openapi: 3.0.1

info:
  title: sap_profile_ms Api
  version: v1
  description: ASP.NET Core 3.1 + MySQL. 
  license:
    name: HangedDraw, 2020-I

servers:
  - url: 'host:8000/api'


paths:
  /Register:
    post:
      tags:
        - User
      summary: 'Registrarse'
      description: 'Petición post para registrar un usuario en la base de datos'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewModelUser'
          text/json:
            schema:
              $ref: '#/components/schemas/ViewModelUser'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ViewModelUser'
      responses:
        '200':
          description: Devuelve si hubo algun error y la respuesta asociada
        '500':
          description: Ocurre una excepción
  /Verify/{id}:
    get:
      tags:
        - User
      summary: 'Verificar correo'
      description: 'Petición get para verificar la cuenta de usuario'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      responses:
        '200':
          description: Devuelve si hubo algun error y la respuesta asociada
        '500':
          description: Ocurre una excepción
  /UserInfo/{id}:
    get:
      tags:
        - User
      summary: 'Obtener información de usuario'
      description: 'Petición get para obtener la información del usuario de id {id}'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      responses:
        '200':
          description: Devuelve si hubo algun error y la información de usuario si no hubo error
        '401':
          description: No autorizado
      security: 
        - bearerAuth: []
  /DeleteUser/{id}:
    delete:
      tags:
        - User
      summary: 'Eliminar usuario'
      description: 'Petición delete para eliminar el usuario de id {id}'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      responses:
        '200':
          description: Devuelve si hubo un error y el usuario eliminado si no hubo error
        '500':
          description: Ocurre una excepción
        '401':
          description: No autorizado
      security: 
        - bearerAuth: []
  /EditUser/{id}:
    put:
      tags:
        - User
      summary: 'Editiar información de perfil'
      description: 'Petición put para cambiar información del usuario de id {id}'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewModelUser'
          text/json:
            schema:
              $ref: '#/components/schemas/ViewModelUser'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ViewModelUser'
      responses:
        '200':
          description: Devuelve si hubo algún error al modificar algo de información del usuario
        '500':
          description: Ocurre una excepción
        '401':
          description: No autorizado
      security: 
        - bearerAuth: []
  /ChangePasswordUser/{id}:
    put:
      tags:
        - User
      summary: 'Cambiar contraseña'
      description: 'Petición put para cambiar contraseña del usuario de id {id}'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewModelPassword'
          text/json:
            schema:
              $ref: '#/components/schemas/ViewModelPassword'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ViewModelPassword'
      responses:
        '200':
          description: devuelve si hubo error y la respuesta asociada
        '500':
          description: Ocurre una excepción
        '401':
          description: No autorizado
      security: 
        - bearerAuth: []
  /RequestPasswordChange/{email}:
    post:
      tags:
        - User
      summary: 'Petición Reestablecer contraseña'
      description: 'Petición post para solicitar cambio de contraseña del usuario con correo electronico {email}. Se envía un correo para verificar el correo y un link para reestablecer la contraseña'
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Devuelve si hubo algún error y la respuesta asociada
        '500':
          description: Ocurre una excepción
  /ChangePassword/{id}/{token}:
    put:
      tags:
        - User
      summary: 'Reestablecer contraseña'
      description: 'Petición post para cambiar de contraseña del usuario de id {id}. Se envía un correo para verificar el correo y un link para reestablecer la contraseña'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewModelPassword'
          text/json:
            schema:
              $ref: '#/components/schemas/ViewModelPassword'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ViewModelPassword'
      responses:
        '200':
          description: Devuelve si hubo algún error y la respuesta asociada
        '500':
          description: Ocurre una excepción
  /Login:
    post:
      tags:
        - User
      summary: 'Iniciar sesión'
      description: 'Petición post para iniciar sesión'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewModelLogin'
          text/json:
            schema:
              $ref: '#/components/schemas/ViewModelLogin'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ViewModelLogin'
      responses:
        '200':
          description: Devuelve si hubo algún error y la respuesta asociada
  /UploadFile:
    post:
      tags:
        - User
      summary: 'Subir foto de perfil'
      description: 'Petición post para subir un archivo'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewModelUploadFile'
          text/json:
            schema:
              $ref: '#/components/schemas/ViewModelUploadFile'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ViewModelUploadFile'
      responses:
        '200':
          description: Devuelve si hubo algún error y la respuesta asociada

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ViewModelUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        lastName:
          type: string
        userName:
          type: string
        email:
          type: string
        password:
          type: string
        confirmedPassword:
          type: string
        country:
          type: string
        picture:
          type: string
        imageBytes:
          type: string
          format: byte
        totalGames:
          type: integer
          format: int32
        wonGames:
          type: integer
          format: int32
        lostGames:
          type: integer
          format: int32
      required:
        - name
        - lastName
        - userName
        - email
        - password
        - confirmedPassword
        - country
    ViewModelPassword:
      type: object
      properties:
        password:
          type: string
        confirmedPassword:
          type: string
      required:
        - password
        - confirmedPassword
    ViewModelLogin:
      type: object
      properties:
        userName:
          type: string
        password:
          type: string
      required:
        - password
        - confirmedPassword
    ViewModelUploadFile:
      type: object
      properties:
        file:
          type: string
          format: byte
        fileName:
          type: string
      required:
        - file
        - fileName
